# -*- coding: utf-8 -*-
"""attendance.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1a6TQyXC99u_vJiF2T2ZTfXzFypl1ADBJ
"""

!pip install face_recognition opencv-python-headless

import cv2
import os
import csv
import pickle
import base64
import numpy as np
import face_recognition
from datetime import datetime
from IPython.display import display, Javascript
from google.colab.output import eval_js

def take_multiple_frames(n=5):
    display(Javascript(f"""
    async function captureMultiple() {{
        const div = document.createElement('div');
        const video = document.createElement('video');
        const button = document.createElement('button');
        const info = document.createElement('p');

        button.textContent = '📸 Capture Next';
        info.textContent = 'Click button to capture images';
        div.appendChild(info);
        div.appendChild(video);
        div.appendChild(button);
        document.body.appendChild(div);

        const stream = await navigator.mediaDevices.getUserMedia({{video: true}});
        video.srcObject = stream;
        await video.play();

        let images = [];

        for (let i = 0; i < {n}; i++) {{
            info.textContent = `Capture image ${{i+1}}/{n}`;
            await new Promise(resolve => button.onclick = resolve);

            const canvas = document.createElement('canvas');
            canvas.width = video.videoWidth;
            canvas.height = video.videoHeight;
            canvas.getContext('2d').drawImage(video, 0, 0);

            images.push(canvas.toDataURL('image/jpeg', 0.8));
        }}

        stream.getTracks().forEach(track => track.stop());
        div.remove();
        return images;
    }}
    """))

    data = eval_js("captureMultiple()")

    frames = []
    for img in data:
        decoded = base64.b64decode(img.split(",")[1])
        frame = cv2.imdecode(np.frombuffer(decoded, np.uint8), cv2.IMREAD_COLOR)
        frames.append(frame)

    return frames

class FaceAttendanceSystemColab:
    def __init__(self):
        self.encodings_file = "face_encodings.pkl"
        self.attendance_file = "attendance_log.csv"
        self.known_faces = {}  # name -> list of encodings

        os.makedirs("registered_faces", exist_ok=True)
        self.load_encodings()

        if not os.path.exists(self.attendance_file):
            with open(self.attendance_file, "w", newline="") as f:
                writer = csv.writer(f)
                writer.writerow(["Name", "Date", "Time", "Status"])

    def save_encodings(self):
        with open(self.encodings_file, "wb") as f:
            pickle.dump(self.known_faces, f)

    def load_encodings(self):
        if os.path.exists(self.encodings_file):
            with open(self.encodings_file, "rb") as f:
                self.known_faces = pickle.load(f)
            print(f"✅ Loaded {len(self.known_faces)} registered persons")
        else:
            self.known_faces = {}

    def register_face(self, name, samples=5):
        print(f"\n📸 Registering {name} ({samples} images)")

        if name not in self.known_faces:
            self.known_faces[name] = []

        for i in range(samples):
            print(f"➡️ Capture image {i+1}/{samples}")
            frame = take_frame()
            rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

            locations = face_recognition.face_locations(rgb)
            if not locations:
                print("❌ No face detected, retry")
                continue

            encoding = face_recognition.face_encodings(rgb, locations)[0]
            self.known_faces[name].append(encoding)

            cv2.imwrite(f"registered_faces/{name}_{i+1}.jpg", frame)

        self.save_encodings()
        print(f"✅ {name} registered with {len(self.known_faces[name])} images")

    def mark_attendance(self, name):
        now = datetime.now()
        date = now.strftime("%Y-%m-%d")
        time = now.strftime("%H:%M:%S")

        with open(self.attendance_file, "a", newline="") as f:
            writer = csv.writer(f)
            writer.writerow([name, date, time, "Present"])

        print(f"✅ Attendance marked for {name}")

    def run_attendance(self):
        print("\n📷 Capture image for attendance")
        frame = take_frame()
        rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)

        locations = face_recognition.face_locations(rgb)
        encodings = face_recognition.face_encodings(rgb, locations)

        if not encodings:
            print("❌ No face detected")
            return

        for face_encoding in encodings:
            best_name = "Unknown"
            best_distance = 1.0

            for name, enc_list in self.known_faces.items():
                distances = face_recognition.face_distance(enc_list, face_encoding)
                avg_distance = np.mean(distances)

                if avg_distance < best_distance:
                    best_distance = avg_distance
                    best_name = name

            if best_distance < 0.55:
                self.mark_attendance(best_name)
            else:
                print("❌ Unknown face detected")

    def view_attendance(self):
        print("\n📊 Attendance Log")
        with open(self.attendance_file) as f:
            for row in csv.reader(f):
                print(row)

system = FaceAttendanceSystemColab()

system.register_face("Ahmad", samples=5)
system.register_face("Danial", samples=5)
system.register_face("Mark", samples=5)

system.run_attendance()

system.view_attendance()

